# Generated by Django 4.1 on 2022-09-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missoesmodel',
            name='aberta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='missoesmodel',
            name='foto_missao',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
