# Generated by Django 4.1 on 2022-09-03 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0001_initial'),
        ('fichas', '0002_ficharpgmodel_jogador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficharpgmodel',
            name='jogador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jogadores.jogador'),
        ),
    ]
