# Generated by Django 4.1 on 2022-09-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0003_alter_ficharpgmodel_jogador'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficharpgmodel',
            name='is_dead',
            field=models.BooleanField(default=False),
        ),
    ]
