# Generated by Django 4.1 on 2022-09-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0004_ficharpgmodel_is_dead'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficharpgmodel',
            name='foto_personagem',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
